<a href="https://colab.research.google.com/github/deepesh16b/ML/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY TUTORIAL**


In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,5,6], [1,2,3,4]], np.int64)

In [3]:
myarr

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [4]:
myarr.shape

(2, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,2] = 8

In [7]:
myarr

array([[3, 4, 8, 6],
       [1, 2, 3, 4]])

In [8]:
myarr.size

8

In [9]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [10]:
zeros = np.zeros((2,3))

In [11]:
rng = np.arange(10)

In [25]:
lspace = np.linspace(1,30,5)

In [26]:
lspace

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [29]:
emp = np.empty((3,2))

In [30]:
emp

array([[ 1. ,  6.8],
       [12.6, 18.4],
       [24.2, 30. ]])

In [31]:
emp_like = np.empty_like(lspace)

In [32]:
emp_like

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [35]:
arr = np.arange(15)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
ar = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar.sum(axis=0)

array([12, 15, 18])

In [45]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
ar.flat

In [54]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [56]:
ar.ndim

2

In [57]:
ar.size

9

In [59]:
ar.nbytes

72

In [60]:
ar.argmax()

8

In [62]:
ar.flat[ar.argmax()]

9

In [63]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [64]:
ar.argmax(axis=0)

array([2, 2, 2])

In [67]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
ar2 = np.array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
ar + ar2

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [74]:
ar * ar2

array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 18]])

In [75]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [76]:
ar.max()

9

In [77]:
np.where(ar>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [78]:
type(np.where(ar>5))

tuple